name: Deploy Lingo-FE

on:
    pull_request:
        branches: ["release"]
        types: ["closed"]
    push:
        branches: ["release"]

env:
    HOST: ${{secrets.HOST}}
    PORT: ${{secrets.PORT}}
    USERNAME: ${{secrets.USERNAME}}
    PASSWORD: ${{secrets.PASSWORD}}
    IMAGE_NAME: lingo-client

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Create Env Variables
              run: |
                  echo "${{secrets.PRODUCTION_ENV}}" > ./env.production

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Dockerhub login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: |
                  docker buildx create --use
                  docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t ${{ env.IMAGE_NAME }} .

            - name: Push Image to Dockerhub
              run: |
                  docker buildx tag ${{env.IMAGE_NAME}} ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest
                  docker push ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest

            - name: Pull Docker Image and Restart Container
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ env.HOST }}
                  username: ${{ env.USERNAME }}
                  key: ${{ env.PASSWORD }}
                  port: ${{ env.PORT }}

                  # 기존 컨테이너 제거 및 이미지 제거 후 태그 지정후 컨테이너 재시작
                  script: |
                      docker stop ${{env.IMAGE_NAME}}
                      docker rm ${{env.IMAGE_NAME}}
                      docker rmi ${{ env.IMAGE_NAME }}:latest
                      docker pull ${{secrets.DOCKER_USER}}/${{ env.IMAGE_NAME }}:latest
                      docker run -p 80:3000 -d --name ${{env.IMAGE_NAME}}:latest ${{env.IMAGE_NAME}}
